[project]
name = "binsbom"
version = "0.1.1"
description = "Binary scanner that emits an SBOM (CycloneDX JSON)"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [{name = "You", email = "you@example.com"}]
dependencies = [
  "cyclonedx-python-lib>=6.0.0",
  "lief>=0.14.1; platform_system == 'Linux' or platform_system == 'Windows' or platform_system == 'Darwin'",
  "pefile>=2023.2.7; platform_system == 'Windows'",
  "pyelftools>=0.31"
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[project.scripts]
binsbom = "binsbom.cli:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"